apiVersion: v1
kind: Service
metadata:
  name: git-server
  labels:
    app: git-server
spec:
  type: NodePort
  ports:
  - port: 8000
  selector:
    app: git-server
---
apiVersion: v1
kind: Service
metadata:
  name: gitlist
  labels:
    app: gitlist
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: gitlist